version: '3'

services:
  front:
    image: node:16-alpine3.11
    working_dir: /home/app
    container_name: shipment_front
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
    volumes:
      - ./front:/home/app
    ports:
      - 3000:3000
    command: >
      sh -c "npm install && npm run start"

  server:
    image: node:16-alpine3.11
    working_dir: /home/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=8000
    volumes:
      - ./server:/home/app
    ports:
      - 8000:8000
    container_name: shipment_server
    command: >
      sh -c "npm install && npm start"
